{% set name = "blackrenderer" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/blackrenderer-{{ version }}.tar.gz
  sha256: 13c97569c4b05c0e9f7c4e85af4f4a8ac9c3e76bd6a43e2c5307b4df25ac11c6

build:
  entry_points:
    - blackrenderer=blackrenderer.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fonttools >=4.34.0
    - uharfbuzz >=0.16.0

test:
  imports:
    - blackrenderer
  commands:
    - pip check
    - blackrenderer --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BlackFoundryCom/black-renderer
  summary: A Python-based renderer for OpenType COLRv1 fonts, with multiple backends.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
