{% set name = "blackrenderer" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/blackrenderer-{{ version }}.tar.gz
  sha256: 639e30d2ddd080e90780e45130ac202c5f4f5180db5d6c48f61a222d58560952

build:
  entry_points:
    - blackrenderer=blackrenderer.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fonttools >=4.34.0
    - uharfbuzz >=0.16.0

test:
  imports:
    - blackrenderer
  commands:
    - pip check
    - blackrenderer --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BlackFoundryCom/black-renderer
  summary: A Python-based renderer for OpenType COLRv1 fonts, with multiple backends.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
